target-version = "py312"
line-length = 320

[lint]
select = ["ALL"]
ignore = ["ANN401", "BLE" ,"D", "E501", "EM", "PD002", "PD901", "PLC01", "PLR09", "PLR2004", "PTH123", "TCH"]

[lint.per-file-ignores]
"**/tests/*" = ["S101"]